language: php
sudo: required
php:
  - 5.6
  - 7.0
install:
  - sudo apt-get update
  - sudo chmod +x install/install.sh
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 2
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 3
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 4
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 7
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 8
  - sudo php install/install.php mode=force
  - sudo chmod 777 -R /home/travis/build/jeedom
  - sudo chown www-data:www-data -R /home/travis/build/jeedom
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 12