language: php
sudo: required
install:
  - sudo ./install/install.sh
  - php install/install.php mode=force
php:
  - 5.6
  - 7.0
branches:
  except:
    - stable
after_success:
	- sudo ./travis/after_success.sh