language: php
sudo: required
php:
  - 5.6
  - 7.0
services:
  - mysql
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'jeedom'@'%' IDENTIFIED BY 'jeedom';" | mysql -uroot
  - mysql -e "DROP DATABASE IF EXISTS jeedom;" | mysql -uroot
  - mysql -e "CREATE DATABASE jeedom;" | mysql -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON jeedom.* TO 'jeedom'@'%';" | mysql -uroot
install:
  - sudo apt-get -y install ca-certificates ntp
  - cp core/config/common.config.sample.php core/config/common.config.php
  - sed -i "s/#PASSWORD#/jeedom/g" core/config/common.config.php 
  - sed -i "s/#DBNAME#/jeedom/g" core/config/common.config.php 
  - sed -i "s/#USERNAME#/jeedom/g" core/config/common.config.php 
  - sed -i "s/#PORT#/3306/g" core/config/common.config.php 
  - sed -i "s/#HOST#/127.0.0.1/g" core/config/common.config.php 
  - sudo chmod 775 -R *
  - sudo chown -R www-data:www-data *
  - php install/install.php mode=force
  - sudo mkdir /home/travis/build/jeedom/plugins
  - sudo chmod 777 -R /home/travis/build/jeedom
  - sudo chown www-data:www-data -R /home/travis/build/jeedom