on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - alpha
      - beta
  pull_request:
    branches:
      - alpha
      - beta
      - V4-stable
      
name : 'Code Lint Global'

jobs:
  run-linters:
    name: Test Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: phpcs

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm i prettier

      - name: Install Python dependencies
        run: pip install flake8 black

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          prettier: true
          prettier_extensions: css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml
          auto_fix: true
          prettier_auto_fix: true
          git_email: commit@jeedom.com
          git_name: 'JeedomBot lint Pretty'
          commit: false
          black: true
          black_auto_fix: true
